### ISSUE TITLE
Thread panics in demo - "Not supported"

### ISSUE THREAD

**Issue by Ploppz** [myfreeweb/unixbar#1]
```
$ cargo run --example demo | lemonbar | bash
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/demo`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Not supported") }) }', /checkout/src/libcore/result.rs:860
stack backtrace:
   0:       0x4ef99d12d3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hcab99e0793da62c7
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:       0x4ef99ce036 - std::sys_common::backtrace::_print::hbfe5b0c7e79c0711
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:       0x4ef99d53da - std::panicking::default_hook::{{closure}}::h9ba2c6973907a2be
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:       0x4ef99d4fdb - std::panicking::default_hook::he4d55e2dd21c3cca
                               at /checkout/src/libstd/panicking.rs:371
   4:       0x4ef99d57eb - std::panicking::rust_panic_with_hook::ha138c05cd33ad44d
                               at /checkout/src/libstd/panicking.rs:549
   5:       0x4ef99d56c4 - std::panicking::begin_panic::hcdbfa35c94142fa2
                               at /checkout/src/libstd/panicking.rs:511
   6:       0x4ef99d55f9 - std::panicking::begin_panic_fmt::hc09fe500d9b7be81
                               at /checkout/src/libstd/panicking.rs:495
   7:       0x4ef99d5587 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:       0x4ef99fe0fd - core::panicking::panic_fmt::h883a028e9f4b4457
                               at /checkout/src/libcore/panicking.rs:69
   9:       0x4ef996afa8 - core::result::unwrap_failed::h318069c47af4263c
                               at /checkout/src/libcore/macros.rs:29
  10:       0x4ef9959bd8 - <core::result::Result<T, E>>::unwrap::h30cecec367ba7357
                               at /checkout/src/libcore/result.rs:738
  11:       0x4ef997c550 - demo::main::{{closure}}::hb1759093c89a6503
                               at examples/demo.rs:37
  12:       0x4ef99479fe - <unixbar::widget::delayed::Delayed<T, F, U> as unixbar::widget::base::Widget>::spawn_notifier::{{closure}}::hc29aebe38a332b27
                               at /home/ploppz/work/rust/unixbar/src/widget/delayed.rs:29
  13:       0x4ef9950eb4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a99b2e6745a17e4
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  14:       0x4ef9954f24 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h7d2716d798239233
                               at /checkout/src/libstd/thread/mod.rs:364
  15:       0x4ef9979304 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h1fcacbf3c12976f8
                               at /checkout/src/libstd/panic.rs:296
  16:       0x4ef9955ae4 - std::panicking::try::do_call::h953ec36979d00925
                               at /checkout/src/libstd/panicking.rs:454
  17:       0x4ef99dc37a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  18:       0x4ef99556e9 - std::panicking::try::ha766032aef8d01ea
                               at /checkout/src/libstd/panicking.rs:433
  19:       0x4ef9952bef - std::panic::catch_unwind::heef7bced2fe9f48b
                               at /checkout/src/libstd/panic.rs:361
  20:       0x4ef9954a84 - std::thread::Builder::spawn::{{closure}}::h9a1901e2b058ac01
                               at /checkout/src/libstd/thread/mod.rs:363
  21:       0x4ef996b18a - <F as alloc::boxed::FnBox<A>>::call_box::h302f5fd36a69754a
                               at /checkout/src/liballoc/boxed.rs:648
  22:       0x4ef99d46e5 - std::sys::imp::thread::Thread::new::thread_start::h227b2afaa9316a8d
                               at /checkout/src/liballoc/boxed.rs:658
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  23:     0x7ff567c27048 - start_thread
  24:     0x7ff56812ff0e - clone
  25:                0x0
```

Cool library, I think I will contribute to it.

**Comment by myfreeweb** [comment]
Thanks!

> unixbar::widget::delayed::Delayed

looks like the CPU usage measurement is not available for your platform yet.

The code for Linux is already there https://github.com/myfreeweb/systemstat/pull/6 I'll merge it soon

**Comment by myfreeweb** [comment]
Linux CPU measurement has been merged

**Comment by Ploppz** [comment]
I came back to this after a while, updated all the repositories and I got this error:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Not supported") }) }', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0:     0x557ed2a7ea83 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h6072fc713498e3e8
WMDVI-0:o17:o2:f3:f14:f20:o18:o4:o11:O10:LT:TT:G
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x557ed2a7afda - std::sys_common::backtrace::_print::h26fe054bf4f364c0
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x557ed2a826c3 - std::panicking::default_hook::{{closure}}::hd530f98a72c74adb
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x557ed2a82432 - std::panicking::default_hook::h73253e103e248e51
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x557ed2a82b87 - std::panicking::rust_panic_with_hook::had8e47d1d1e27fbd
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x557ed2a829e4 - std::panicking::begin_panic::h2efab78c3119edd9
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x557ed2a82959 - std::panicking::begin_panic_fmt::h43b1c41b0d313aa4
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x557ed2a828ea - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x557ed2ab9e30 - core::panicking::panic_fmt::h672d5b61d83def59
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x557ed29aaee7 - core::result::unwrap_failed::h72060e99bde12a95
                               at /checkout/src/libcore/macros.rs:23
  10:     0x557ed2950119 - <core::result::Result<T, E>>::unwrap::h47c6330ee5fed731
                               at /checkout/src/libcore/result.rs:772
  11:     0x557ed2955400 - green::main::{{closure}}::h6b5e5c858e94c399
                               at src/main.rs:48
  12:     0x557ed294e84c - <unixbar::widget::delayed::Delayed<T, F, U> as unixbar::widget::base::Widget>::spawn_notifier::{{closure}}::hf1d9c6941e7fcfa0
                               at /home/ploppz/work/rust/unixbar/unixbar/src/widget/delayed.rs:28
  13:     0x557ed294f884 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7335b8915ec42d57
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  14:     0x557ed29b4768 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h1f6475e8c063501e
                               at /checkout/src/libstd/thread/mod.rs:394
  15:     0x557ed29b40c4 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2580a2d7babf06ab
                               at /checkout/src/libstd/panic.rs:296
  16:     0x557ed29893be - std::panicking::try::do_call::h1d6a90c9d7f3db70
                               at /checkout/src/libstd/panicking.rs:480
  17:     0x557ed2a899dc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  18:     0x557ed2988a59 - std::panicking::try::h543d7baf6aaf866e
                               at /checkout/src/libstd/panicking.rs:459
  19:     0x557ed29b45ef - std::panic::catch_unwind::h857cb94e92cf1e80
                               at /checkout/src/libstd/panic.rs:361
  20:     0x557ed2976e0f - std::thread::Builder::spawn::{{closure}}::h33620b248ed13ca5
                               at /checkout/src/libstd/thread/mod.rs:393
  21:     0x557ed2979709 - <F as alloc::boxed::FnBox<A>>::call_box::hc452eb82de8fbf33
                               at /checkout/src/liballoc/boxed.rs:682
  22:     0x557ed2a81b1b - std::sys::imp::thread::Thread::new::thread_start::h3d10a34c71b21db8
                               at /checkout/src/liballoc/boxed.rs:692
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  23:     0x7efc0f2f8089 - start_thread
  24:     0x7efc0fd4a47e - __clone
  25:                0x0 - <unknown>
```

The line in my `main.rs` is the last line of this:
```
        .add(Delayed::new(
             Duration::from_secs(1),
             || System::new().cpu_load_aggregate().unwrap(),

```

Any idea?

**Comment by myfreeweb** [comment]
Hmm, make sure systemstat master is used. unixbar depends on systemstat from crates.io, that version hasn't been updated to include CPU load on Linux.

Currently in my bar:

```
//! ```cargo
//! [dependencies]
//! unixbar = { path = "/home/greg/src/github.com/myfreeweb/unixbar" }
//! systemstat = { path = "/home/greg/src/github.com/myfreeweb/systemstat" }
//! [patch.crates-io]
//! systemstat = { path = "/home/greg/src/github.com/myfreeweb/systemstat" }
//! ```
```

**Comment by myfreeweb** [comment]
No leaks on the git master version?

**Comment by Ploppz** [comment]
I experienced no leaks in the git master version.

**Comment by Ploppz** [comment]
Oh actually, I am experiencing leaks but only when it is started through `.bspwmrc` (using bspwm in Linux). In `.bspwmrc`, I have `~/bin/green-bar &`. `green-bar` just contains:

```
#!/bin/bash
~/bin/green | lemonbar -f '*gohufont-medium-*-*-*-11-*' -f '*stlphallus*'
```

However after `killall lemonbar; green-bar`, (or when starting it any other time) there is no leak.

**Comment by myfreeweb** [comment]
That's weird. Does the leak still happen if you remove the bspwm widget?
