### ISSUE TITLE
Panic (apparently in Delayed / cpu load) - subtract with overflow, PoisonError

### ISSUE THREAD

**Issue by Ploppz** [myfreeweb/unixbar#8]
Panicked (while running this https://gist.github.com/Ploppz/ec609784491ae2c2ecbc98d4532c1f0d) on Linux.
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/data.rs:75:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <systemstat::platform::linux::PlatformImpl as systemstat::platform::common::Platform>::cpu_load::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/data.rs:75
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/platform/linux.rs:220
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  12: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  13: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1073
  14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1825
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1808
  16: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1695
  17: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1302
  18: <systemstat::platform::linux::PlatformImpl as systemstat::platform::common::Platform>::cpu_load::{{closure}}::{{closure}}::{{closure}}
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/platform/linux.rs:217
  19: <core::result::Result<T, E>>::map
             at /checkout/src/libcore/result.rs:468
  20: <systemstat::platform::linux::PlatformImpl as systemstat::platform::common::Platform>::cpu_load::{{closure}}::{{closure}}
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/platform/linux.rs:216
  21: systemstat::platform::common::Platform::cpu_load_aggregate::{{closure}}
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/data.rs:28
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/platform/common.rs:22
  22: <unixbar::widget::delayed::Delayed<T, F, U> as unixbar::widget::base::Widget>::spawn_notifier::{{closure}}
             at /home/ploppz/.cargo/git/checkouts/systemstat-39467158cd685114/79570ca/src/data.rs:28
             at /home/ploppz/work/rust/unixbar/unixbar/src/widget/delayed.rs:34
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: <unixbar::widget::delayed::Delayed<T, F, U> as unixbar::widget::base::Widget>::current_value
             at /home/ploppz/work/rust/unixbar/unixbar/src/widget/delayed.rs:20
  12: <unixbar::UnixBar<F>>::show::{{closure}}
             at /home/ploppz/work/rust/unixbar/unixbar/src/lib.rs:46
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  14: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  15: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1073
  16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1825
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1808
  18: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1695
  19: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1302
  20: <unixbar::UnixBar<F>>::show
             at /home/ploppz/work/rust/unixbar/unixbar/src/lib.rs:46
  21: <unixbar::UnixBar<F>>::run
             at /home/ploppz/work/rust/unixbar/unixbar/src/lib.rs:41
  22: green::main
             at src/main.rs:34
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  24: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  25: main
  26: __libc_start_main
  27: _start
```

**Comment by myfreeweb** [comment]
yeah that's in systemstat.

@Xenopathic are you sure the linux cpu measurement is correct? At first glance, `.map(|(now, prev)| (*now - prev).to_cpuload())` the arguments look flipped compared to my bsd code `.map(|(prev, now)| (*now - prev).to_cpuload())`…

**Comment by Xenopathic** [comment]
@myfreeweb I'm sure, the Linux code differs slightly from the BSD code in that the iterators are the other way around, so the args are in the right order. I've just run the example script from systemstat, and a snippet derived from the linked Gist, and cannot reproduce the issue.

Maybe a difference in the format of `/proc/stat`? This is what mine looks like (the relevant bits are the `cpuX` lines):

```
cpu  510323 23 95744 12055216 1486 0 2526 0 0 0
cpu0 119275 21 27677 3016679 537 0 1308 0 0 0
cpu1 128056 0 22340 3015834 295 0 591 0 0 0
cpu2 131981 0 23618 3010705 385 0 336 0 0 0
cpu3 131009 1 22108 3011997 267 0 288 0 0 0
```

**Comment by Ploppz** [comment]
It happens randomly. Sometimes it takes only a minutes or a few before it happens, other times it can stay good for hours.

```
cpu  2252312 19885 362447 46956286 104833 0 6885 0 0 0
cpu0 249449 1988 43287 3818852 16939 0 5568 0 0 0
cpu1 162944 1655 24837 3945094 8400 0 307 0 0 0
cpu2 207093 2310 35831 3870945 24365 0 535 0 0 0
cpu3 154795 1289 23450 3959150 4753 0 77 0 0 0
cpu4 216525 2756 36617 3865423 19871 0 47 0 0 0
cpu5 165589 1843 24182 3949070 3539 0 20 0 0 0
cpu6 236407 2095 38655 3854623 8094 0 271 0 0 0
cpu7 152060 929 22423 3966160 2382 0 11 0 0 0
cpu8 204363 1818 34020 3893942 7073 0 16 0 0 0
cpu9 150121 869 22573 3969233 1305 0 7 0 0 0
cpu10 200358 1255 33915 3897231 6862 0 15 0 0 0
cpu11 152600 1069 22649 3966558 1244 0 4 0 0 0
```

**Comment by Ploppz** [comment]
Finally it crashed. Including the two `/proc/cpu` contents before the crash:
```
cpu  2607142 22703 417913 58846593 108397 0 8501 0 0 0
cpu0 288237 2394 50684 4791846 19465 0 6945 0 0 0
cpu1 191003 1907 28411 4939251 8414 0 378 0 0 0
cpu2 239596 2545 41390 4857594 24514 0 640 0 0 0
cpu3 179971 1407 26907 4956492 4770 0 94 0 0 0
cpu4 250435 3038 42368 4850730 19969 0 54 0 0 0
cpu5 195201 2024 27496 4942090 3545 0 24 0 0 0
cpu6 271245 2418 44876 4838586 8331 0 296 0 0 0
cpu7 176207 1105 25289 4965360 2407 0 12 0 0 0
cpu8 235454 2110 39830 4882126 7327 0 22 0 0 0
cpu9 173060 1009 25472 4969800 1331 0 9 0 0 0
cpu10 231127 1497 39841 4885457 7031 0 17 0 0 0
cpu11 175598 1241 25342 4967256 1288 0 4 0 0 0
intr 114567710 50 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 229716 0 321242 328229 0 0 0 0 0 1158001 0 783 0 2925 0 2542667 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 191794841
btime 1504076106
processes 25396
procs_running 1
procs_blocked 1
softirq 37889636 4 15629000 8646 1165839 433922 0 61402 8595419 0 11995404



cpu  2607168 22703 417914 58847770 108394 0 8501 0 0 0
cpu0 288237 2394 50684 4791945 19465 0 6945 0 0 0
cpu1 191025 1907 28412 4939331 8414 0 378 0 0 0
cpu2 239597 2545 41390 4857692 24514 0 640 0 0 0
cpu3 179971 1407 26907 4956595 4767 0 94 0 0 0
cpu4 250438 3038 42368 4850826 19969 0 54 0 0 0
cpu5 195201 2024 27496 4942189 3545 0 24 0 0 0
cpu6 271245 2418 44876 4838686 8331 0 296 0 0 0
cpu7 176207 1105 25289 4965460 2407 0 12 0 0 0
cpu8 235454 2110 39830 4882226 7327 0 22 0 0 0
cpu9 173060 1009 25472 4969900 1331 0 9 0 0 0
cpu10 231127 1497 39841 4885557 7031 0 17 0 0 0
cpu11 175598 1241 25342 4967356 1288 0 4 0 0 0
intr 114568872 50 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 229716 0 321243 328229 0 0 0 0 0 1158011 0 783 0 2925 0 2542733 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 191796679
btime 1504076106
processes 25396
procs_running 1
procs_blocked 0
softirq 37890002 4 15629172 8646 1165850 433923 0 61402 8595522 0 11995483



thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/ploppz/work/rust/unixbar/systemstat/src/data.rs:75:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <systemstat::platform::linux::PlatformImpl as systemstat::platform::common::Platform>::cpu_load::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/ploppz/work/rust/unixbar/systemstat/src/data.rs:75
             at /home/ploppz/work/rust/unixbar/systemstat/src/platform/linux.rs:221
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  12: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  13: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1073
  14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1825
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1808
  16: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1695
  17: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1302
  18: <systemstat::platform::linux::PlatformImpl as systemstat::platform::common::Platform>::cpu_load::{{closure}}::{{closure}}::{{closure}}
             at /home/ploppz/work/rust/unixbar/systemstat/src/platform/linux.rs:218
  19: <core::result::Result<T, E>>::map
             at /checkout/src/libcore/result.rs:468
  20: <systemstat::platform::linux::PlatformImpl as systemstat::platform::common::Platform>::cpu_load::{{closure}}::{{closure}}
             at /home/ploppz/work/rust/unixbar/systemstat/src/platform/linux.rs:217
  21: systemstat::platform::common::Platform::cpu_load_aggregate::{{closure}}
             at /home/ploppz/work/rust/unixbar/systemstat/src/data.rs:28
             at /home/ploppz/work/rust/unixbar/systemstat/src/platform/common.rs:22
  22: <unixbar::widget::delayed::Delayed<T, F, U> as unixbar::widget::base::Widget>::spawn_notifier::{{closure}}
             at /home/ploppz/work/rust/unixbar/systemstat/src/data.rs:28
             at /home/ploppz/work/rust/unixbar/unixbar/src/widget/delayed.rs:34
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: <unixbar::widget::delayed::Delayed<T, F, U> as unixbar::widget::base::Widget>::current_value
             at /home/ploppz/work/rust/unixbar/unixbar/src/widget/delayed.rs:20
  12: <unixbar::UnixBar<F>>::show::{{closure}}
             at /home/ploppz/work/rust/unixbar/unixbar/src/lib.rs:46
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  14: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  15: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1073
  16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1825
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1808
  18: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1695
  19: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1302
  20: <unixbar::UnixBar<F>>::show
             at /home/ploppz/work/rust/unixbar/unixbar/src/lib.rs:46
  21: <unixbar::UnixBar<F>>::run
             at /home/ploppz/work/rust/unixbar/unixbar/src/lib.rs:41
  22: green::main
             at src/main.rs:34
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  24: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  25: main
  26: __libc_start_main
  27: _start
```

**Comment by Xenopathic** [comment]
Look at cpu3: iowait *dropped* from 4770 to 4767! Thus systemstat underflows the integer when subtracting... I have no idea why this would ever happen, but I suspect the kernel is doing some statistics reshuffling over time, so it moved some iowait to a different statistic. As a workaround to avoid crashing, maybe a subtract that saturates as zero would be appropriate? Or we could expose the negative numbers to the API consumer, but that seems odd...

**Comment by Ploppz** [comment]
The former is fine I think, saturate as zero.
